<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo '<div class="form-group">';
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo '</div>';
echo $this->formRow($form->get('artist'));
echo '<div style="padding:12px 0 0 0"></p>';
echo '<div class="form-group">';
echo $this->formSubmit($form->get('submit'));
echo '</div>';
echo $this->form()->closeTag();
